server.port: 18052

# set topics of input/output channels
# topics are auto-created
spring.cloud.stream.bindings.uppercase-in-0.destination: strings
spring.cloud.stream.bindings.uppercase-out-0.destination: uppercase