server.port: 13000

spring.cloud.stream.bindings.output.destination: rating
spring.cloud.stream.bindings.output.contentType: application/json
# spring.cloud.stream.kafka.binder.brokers: localhost:9092 # (default)


# Producer Properties
spring.cloud.stream.kafka.binder.producerProperties:
  key.serializer: org.apache.kafka.common.serialization.StringSerializer


# Metrics
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always