server.port: 13000

spring.cloud.stream.bindings.output.destination: rating
spring.cloud.stream.bindings.output.contentType: application/json
# spring.cloud.stream.default.messageKeyExpression: headers['key']

# spring.cloud.stream.kafka.binder.brokers: localhost:9092 # (default)