server.port: 18053

# set rate of message production (1000 = 1s)
# spring.integration.poller.fixed-delay: 1000

# define which function method will be triggered if there are multiple
# spring.cloud.function.definition: stringSource

# set topic of stringSource-out-0 channel (default topic = 'stringSource-out-0')
# topic is auto-created
spring.cloud.stream.bindings.stringSource-out-0.destination: strings