server.port: 18062

# set topics of input/output channels
# topics are auto-created
spring.cloud.stream.bindings.reactiveUppercase-in-0.destination: strings
spring.cloud.stream.bindings.reactiveUppercase-out-0.destination: uppercase