global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
- job_name: 'ratings-app'

  metrics_path: '/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['host.docker.internal:13000']

- job_name: 'movie-ratings-app'

  metrics_path: '/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['host.docker.internal:14000']

- job_name: 'movies-app'

  metrics_path: '/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['host.docker.internal:18000']